### ISSUE TITLE
Simplify db configuration

### ISSUE THREAD

**Issue by rm-yakovenko** [rm-yakovenko/docker-nginx-php-mysql#10]
```
    db:
        image: mariadb:10.3
        command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
        ports:
            - 127.0.0.1:13306:3306
        environment:
            - MYSQL_ROOT_PASSWORD
            - MYSQL_DATABASE=laravel
        volumes:
            - /etc/localtime:/etc/localtime:ro
```
